# constants.py

UNITS = {
    'Convergence Rate': 'cm/yr',
    'Migration Rate': 'cm/yr',
    'vratio': "",
    'Subducting Plate Velocity': "cm/yr",
    'Subduction Length': 'm',
    'Slab Dip': "Deg",
    'Subduction Volume Rate': 'km^3/yr',
    'Obliquity Angle': "Deg",
    'Subduction Normal': "Deg",
    'Subduction Flux': "m2/yr",
    'Spreading Rate': 'cm/yr',
    'Elastic Thickness': 'km',
    'LithoCAM2016': 'km',
    'Litho07Sv': 'km',
    'GEMMA': 'km',
    'Crust1': 'km',
    'Precipitation (Pohl et al.)': 'mm',
    'Precipitation (Li et al.)': 'mm',
    'MT_93': 'deg C',
    'MT_140': 'deg C',
    'MT_202': 'deg C',
    'MT_248': 'deg C',
    'MT_293': 'deg C',
    'MT_357': 'deg C',
    'MT_396': 'deg C',
    'Vz_93': 'cm/yr',
    'Vz_140': 'cm/yr',
    'Vz_202': 'cm/yr',
    'Vz_248': 'cm/yr',
    'Vz_293': 'cm/yr',
    'Vz_357': 'cm/yr',
    'Vz_396': 'cm/yr',
    'Mantle Temperature': '$^o$C',
    'Mantle Temperature (d=93km)': '$^o$C',
    'Mantle Temperature (d=140km)':'$^o$C',
    'Mantle Temperature (d=202km)':'$^o$C',
    'Mantle Temperature (d=248km)': '$^o$C',
    'Mantle Temperature (d=293km)': '$^o$C',
    'Mantle Temperature (d=357km)': '$^o$C',
    'Mantle Temperature (d=396km)': '$^o$C',
    'Mantle Velocity': 'cm/yr',
    'Vz (d=47km)': '$^o$C',
    'Vz (d=93km)': '$^o$C',
    'Vz (d=140km)': '$^o$C',
    'Vz (d=202km)': '$^o$C',
    'Vz (d=248km)': '$^o$C',
    'Vz (d=293km)': '$^o$C',
    'Vz (d=357km)': '$^o$C',
    'Vz (d=396km)': '$^o$C',
    'Dynamic Topography': "m",
    'Elevation': 'm',
    'Smoothed Elevation 1': 'm',
    'Smoothed Elevation 2': 'm',
    'Relief 1': 'm',
    'Relief 2': 'm',
    'Precipitation(Li)': 'mm',
    'Plate Thickness': 'm',
    'Nearest Trench Edge': 'm',
    'Convergence Velocity Orthogonal': 'cm/yr',
    'Convergence Velocity Parallel': 'cm/yr',
    'Trench Velocity Orthogonal': 'cm/yr',
    'Subducting  Velocity Orthogonal': 'cm/yr',
    'Trench Velocity Parallel': 'cm/yr',
    'Subducting  Velocity Parallel': 'cm/yr',
    'Sediment Thickness': 'm',
    'Trench Distance': 'km'
}

DEFAULT_CRS="epsg:4326"
ED_PROJ="EPSG:4326"
